#!/bin/bash

# Cronic HTML: cron job report wrapper with template support
#
# Copyright 2020 Anxo Rodriguez https://github.com/anxolin.
# No rights reserved, whatsoever.
# Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/

set -eu

# Constants
CONF_DIR=/etc/cronic-html
CONF_FILE_NAME=cronic-html.conf
CONF_USER_FILE="$HOME/.$CONF_FILE_NAME"
CONF_GLOBAL_FILE="$CONF_DIR/$CONF_FILE_NAME"
TEMPLATE_DEFAULT_FILE="$CONF_DIR/templates/html.tmpl.sh"

# Read config:
#     TEMPLATE_FILE: Path to the template. Allows to override the default template
[ -f "$CONF_GLOBAL_FILE" ] && source "$CONF_GLOBAL_FILE"
[ -f "$CONF_USER_FILE" ] && source "$CONF_USER_FILE"

# Enable debug
[[ ! -z "${DEBUG:-}" ]] && set -x

# Temporal files for script output
TMP=$(mktemp -d)
OUT=$TMP/cronic.out
ERR=$TMP/cronic.err
TRACE=$TMP/cronic.trace

# Run script
set +e
"$@" >$OUT 2>$TRACE
RESULT=$?
set -e

# Capture debug output (set -x)
PATTERN="^${PS4:0:1}\\+${PS4:1}"
if grep -aq "$PATTERN" $TRACE
then
    ! grep -av "$PATTERN" $TRACE > $ERR
else
    ERR=$TRACE
fi

# If the script exited with a non-zero code, or if it printed in the SYSERR
if [ $RESULT -ne 0 -o -s "$ERR" ]
    then

    # Prepare template vars
    COMMAND="$@"
    HOSTNAME="`hostname`"
		NL=$'\n'
    OUT_CONTENT="`cat $OUT`"
    ERR_CONTENT="`cat $ERR`"

		[ ! -z "$OUT_CONTENT" ] && OUT_CONTENT="$NL$OUT_CONTENT"
		[ ! -z "$ERR_CONTENT" ] && ERR_CONTENT="$NL$ERR_CONTENT"
		[ $TRACE != $ERR ] && TRACE_CONTENT="$NL$(cat $TRACE)"
    TRACE_CONTENT="${TRACE_CONTENT:-}"

    # Delegate report to template
    source "${TEMPLATE_FILE:-$TEMPLATE_DEFAULT_FILE}"
fi

# Cleanup
rm -rf "$TMP"

exit $RESULT