#!/bin/bash

# Cronic HTML: cron job report wrapper with template support
#
# Copyright 2020 Anxo Rodriguez https://github.com/anxolin.
# No rights reserved, whatsoever.
# Public Domain CC0: http://creativecommons.org/publicdomain/zero/1.0/

set -eu

TMP=$(mktemp -d)
OUT=$TMP/cronic.out
ERR=$TMP/cronic.err
TRACE=$TMP/cronic.trace

set +e
"$@" >$OUT 2>$TRACE
RESULT=$?
set -e

PATTERN="^${PS4:0:1}\\+${PS4:1}"
if grep -aq "$PATTERN" $TRACE
then
    ! grep -av "$PATTERN" $TRACE > $ERR
else
    ERR=$TRACE
fi

if [ $RESULT -ne 0 -o -s "$ERR" ]
    then

    COMMAND="$@"
		NL=$'\n'
    OUT_CONTENT="`cat $OUT`"
    ERR_CONTENT="`cat $ERR`"

		[ ! -z "$OUT_CONTENT" ] && OUT_CONTENT="$NL$OUT_CONTENT"
		[ ! -z "$ERR_CONTENT" ] && ERR_CONTENT="$NL$ERR_CONTENT"
		[ $TRACE != $ERR ] && TRACE_CONTENT="$NL$(cat $TRACE)"

    source "./templates/plain.tmpl.sh" 
fi

rm -rf "$TMP"

exit $RESULT